name: lambda-core
version: '0.1'
synopsis: Simple language
author: Dominic Orchard
copyright: 2019 authors
license: BSD3
dependencies:
- base >=4.10 && <5

ghc-options:
- -O0
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-unused-matches
- -Wno-name-shadowing
- -Wno-type-defaults

executables:
  lcore:
    main: Main.hs
    source-dirs: .
    ghc-options: -main-is Lam
    build-tools:
     - alex
     - happy
    dependencies:
     - directory
     - transformers
     - filepath
     - array
     - text
